#!/usr/bin/env python3
"""WordPress dump -> blog schema migration generator.

Reads _migration/backup/database.sql (All-in-One WP Migration dump with
SERVMASK_PREFIX_ tables), converts posts/pages/comments/terms/options and
emits migrated_data.sql (INSERTs for blog_* tables) plus a markdown report.
"""
import re, html, hashlib, io, os, sys, datetime, urllib.parse
from markdownify import markdownify as md

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SQL_PATH = os.path.join(ROOT, "_migration", "backup", "database.sql")
OUT_SQL = os.path.join(ROOT, "_migration", "migrated_data.sql")
OUT_REPORT = os.path.join(ROOT, "_migration", "migration_report.md")

OLD_HOSTS = ["https://8.163.87.253", "http://8.163.87.253",
             "https://123.56.196.243", "http://123.56.196.243",
             "https://20260006.xyz", "http://20260006.xyz",
             "https://www.20260006.xyz", "http://www.20260006.xyz"]

# The generic parser above is fragile; use a robust tokenizer instead.
def parse_values_robust(s: str):
    rows = []
    i, n = 0, len(s)
    while i < n:
        if s[i] != "(":
            i += 1
            continue
        # parse one tuple
        i += 1
        vals = []
        cur = None       # None => not in token; '' => in token (string)
        in_str = False
        buf = []
        while i < n:
            c = s[i]
            if in_str:
                if c == "\\" and i + 1 < n:
                    m = {"n": "\n", "r": "\r", "t": "\t", "0": "\0", "Z": "\x1a"}.get(s[i+1], s[i+1])
                    buf.append(m); i += 2
                    continue
                if c == "'":
                    if i + 1 < n and s[i+1] == "'":
                        buf.append("'"); i += 2; continue
                    in_str = False
                    vals.append("".join(buf)); buf = []; i += 1; continue
                buf.append(c); i += 1; continue
            # not in string
            if c == "'":
                in_str = True; i += 1; continue
            if c == "," or c == ")":
                if buf:
                    t = "".join(buf).strip()
                    vals.append(None if t.upper() == "NULL" else t)
                    buf = []
                if c == ",":
                    i += 1; continue
                rows.append(vals)
                i += 1
                break
            buf.append(c); i += 1
        else:
            break
        # skip to next tuple start
        while i < n and s[i] in ",; \n\r":
            i += 1
    return rows

def load_tables():
    sql = open(SQL_PATH, encoding="utf-8", errors="replace").read()
    tables = {}
    for m in re.finditer(r"INSERT INTO `SERVMASK_PREFIX_(\w+)` VALUES (.*?);\n", sql, re.S):
        t, body = m.group(1), m.group(2)
        tables.setdefault(t, []).extend(parse_values_robust(body))
    return tables

def rewrite_url(text):
    if not text:
        return text
    for h in OLD_HOSTS:
        text = text.replace(h, "")
    text = text.replace("/wp-content/uploads/", "/uploads/")
    return text

def strip_gutenberg(html_text):
    return re.sub(r"<!--\s*/?wp:[^>]*-->\n?", "", html_text or "")

def html_to_md(html_text):
    if not html_text or not html_text.strip():
        return ""
    html_text = strip_gutenberg(html_text)
    if not html_text.strip():
        return ""
    m = md(html_text, heading_style="ATX", bullets="-", strip=["script", "style"])
    # markdownify likes escaped chars; keep it readable
    m = m.replace("\\\n", "\n")
    m = re.sub(r"\n{3,}", "\n\n", m).strip()
    return m

def slugify(name, fallback):
    s = name.strip().lower()
    s = re.sub(r"[^a-z0-9\-_]+", "-", s).strip("-")
    return s or fallback

def q(v):
    if v is None:
        return "NULL"
    v = str(v).replace("\\", "\\\\").replace("'", "''").replace("\n", "\\n").replace("\r", "\\r")
    return "'" + v + "'"

def main():
    t = load_tables()
    posts = {int(r[0]): r for r in t.get("posts", [])}
    terms = {int(r[0]): r for r in t.get("terms", [])}
    tt = {int(r[0]): r for r in t.get("term_taxonomy", [])}
    rels = t.get("term_relationships", [])
    comments = sorted((r for r in t.get("comments", [])), key=lambda r: int(r[0]))
    postmeta = {}
    for r in t.get("postmeta", []):
        postmeta.setdefault(int(r[1]), {})[r[2]] = r[3]
    options = {r[1]: r[2] for r in t.get("options", [])}

    # taxonomy maps: term_taxonomy_id -> (term_id, taxonomy)
    tax_of = {k: (int(v[1]), v[2]) for k, v in tt.items()}

    lines = ["-- Generated by migrate_wp.py  (导入前确保已执行 Flyway V1__schema.sql 建表)",
             "SET NAMES utf8mb4;", "START TRANSACTION;"]

    # ---------- posts ----------
    type_map = {"post": 0, "page": 1, "shuoshuo": 2}
    status_map = {"publish": 1, "draft": 0, "private": 0, "pending": 0, "future": 0, "trash": None}
    # 文章封面轮换（原站未设特色图片，使用风景壁纸素材）
    cover_pool = ["/uploads/bg/cover-3.png", "/uploads/bg/light.png", "/uploads/bg/dark.png"]
    n_posts = 0
    used_slugs = set()
    type_counter = {}
    for pid, p in sorted(posts.items()):
        (pid_, author, pdate, pdate_gmt, content, title, excerpt, pstatus,
         cstatus, pstatus2, ppassword, pname, to_ping, pinged, pmodified,
         pmodified_gmt, content_filtered, post_parent, guid, menu_order,
         ptype, mime, ccount) = p[:23]
        ccount = int(ccount or 0)
        type_counter[ptype] = type_counter.get(ptype, 0) + 1
        if ptype not in type_map or status_map.get(pstatus) is None:
            continue  # attachment/revision/trash skip
        btype = type_map[ptype]
        bstatus = status_map[pstatus]
        if ppassword:
            bstatus = 2
        content = rewrite_url(content)
        content_md = html_to_md(content) if btype != 2 else re.sub(r"<[^>]+>", "", strip_gutenberg(content)).strip()
        summary = rewrite_url(excerpt) or ""
        if btype == 2:
            title_out = title or ""
            slug = None
        else:
            title_out = title or "(无标题)"
            slug = urllib.parse.unquote(pname) if pname else None
            if not slug:
                slug = f"post-{pid}"
            base = slug; k = 2
            while slug in used_slugs:
                slug = f"{base}-{k}"; k += 1
            used_slugs.add(slug)
        views = int(postmeta.get(pid, {}).get("views") or postmeta.get(pid, {}).get("post_views_count") or 0)
        published = pdate if bstatus in (1, 2) else None
        created = pmodified or pdate
        cover = cover_pool[n_posts % len(cover_pool)] if btype == 0 else None
        lines.append(
            "INSERT INTO blog_post (id,type,title,slug,content_md,summary,cover,status,password,author_id,views,is_top,allow_comment,comment_count,published_at,create_time) VALUES ("
            f"{pid},{btype},{q(title_out)},{q(slug)},{q(content_md)},{q(summary[:500])},{q(cover)},"
            f"{bstatus},{q(ppassword or None)},1,{views},0,{'0' if cstatus=='closed' else '1'},{ccount},{q(published)},{q(created)});"
        )
        n_posts += 1

    # ---------- categories / tags ----------
    cat_rows, tag_rows = [], []
    for ttid, (term_id, tax) in sorted(tax_of.items()):
        term = terms.get(term_id)
        if not term:
            continue
        name, tslug = term[1], term[2] or slugify(term[1], f"term-{term_id}")
        if tax == "category":
            cat_rows.append((ttid, name, tslug))
        elif tax == "post_tag":
            tag_rows.append((ttid, name, tslug))
    for cid, name, tslug in cat_rows:
        lines.append(f"INSERT INTO blog_category (id,name,slug,description,sort_order) VALUES ({cid},{q(name)},{q(tslug)},NULL,0);")
    for tid, name, tslug in tag_rows:
        lines.append(f"INSERT INTO blog_tag (id,name,slug) VALUES ({tid},{q(name)},{q(tslug)});")

    # ---------- relationships ----------
    for r in rels:
        obj, ttid = int(r[0]), int(r[1])
        if obj not in posts or ttid not in tax_of:
            continue
        ptype = posts[obj][20]
        if ptype not in type_map or status_map.get(posts[obj][7]) is None:
            continue
        term_id, tax = tax_of[ttid]
        table = {"category": "blog_post_category", "post_tag": "blog_post_tag"}[tax]
        lines.append(f"INSERT IGNORE INTO {table} (post_id,{ 'category_id' if tax=='category' else 'tag_id'}) VALUES ({obj},{ttid});")

    # ---------- comments ----------
    def root_of(cid):
        seen = set()
        cur = int(cid)
        while True:
            c = next((x for x in comments if int(x[0]) == cur), None)
            if not c:
                return cur
            parent = int(c[13] or 0)
            if parent in (0, cur) or parent in seen:
                return cur if parent == 0 else parent
            seen.add(cur)
            cur = parent

    appr_map = {"1": 1, "0": 0, "spam": 2}
    n_comments = 0
    for c in comments:
        (cid, cpost, cauthor, cemail, curl, cip, cdate, cdate_gmt, ccontent,
         ckarma, cappr, cagent, ctype, cparent, cuser) = c[:15]
        cpost = int(cpost)
        if str(cappr) not in appr_map:
            continue  # 回收站/未知状态不迁移
        if cpost not in posts or posts[cpost][20] not in type_map:
            continue
        st = appr_map.get(str(cappr), 1)
        content_md = html_to_md(ccontent) or ccontent.strip()
        lines.append(
            "INSERT INTO blog_comment (id,post_id,parent_id,root_id,author,email,website,content_md,content_html,ip,user_agent,status,is_admin,create_time) VALUES ("
            f"{cid},{int(cpost)},{int(cparent or 0)},{root_of(cid)},{q(cauthor)},{q(cemail)},{q(curl)},"
            f"{q(content_md)},NULL,{q(cip)},{q(cagent[:500])},{st},0,{q(cdate)});")
        n_comments += 1

    # ---------- settings ----------
    def opt(key, default=None):
        v = options.get(key)
        return v if v not in (None, "") else default

    site_title = opt("blogname", "我的博客")
    site_sub = opt("blogdescription", "")
    banner_title = opt("argon_banner_title", site_title)
    banner_sub = opt("argon_banner_subtitle", site_sub)
    banner_img = rewrite_url(opt("argon_banner_background_url") or "")
    banner_color = opt("argon_banner_background_color", "#5e72e4")
    typing = "1" if (opt("argon_enable_typing_effect") or "false") in ("true", "1", "True") else "0"
    dark = "1" if (opt("argon_enable_dark_mode") or "false") in ("true", "1", "True") else "0"
    footer = opt("argon_footer_text", "")
    allow_comment = "0" if opt("comment_moderation") in ("1",) else "1"
    icp = opt("argon_custom_css", "")  # no direct icp; leave empty
    settings = {
        "siteTitle": site_title, "siteSubtitle": site_sub,
        "bannerTitle": banner_title, "bannerSubtitle": banner_sub,
        "bannerImage": "" if banner_img == "--bing--" else banner_img,
        "bannerSource": "bing" if banner_img == "--bing--" else "custom",
        "bannerTypingEffect": typing,
        "darkModeDefault": "auto" if dark == "1" else "light",
        "footerText": footer, "icpText": "", "allowComment": allow_comment,
        "siteUrl": "https://blog.20260006.xyz",
        # 页面背景（Argon 的 page_background_* 设置）
        "pageBackgroundImage": "/uploads/bg/light.png",
        "pageBackgroundImageDark": "/uploads/bg/dark.png",
        "pageBackgroundOpacity": opt("argon_page_background_opacity", "0.6"),
    }
    for k, v in settings.items():
        lines.append(f"INSERT INTO blog_setting (setting_key,setting_value) VALUES ({q(k)},{q(v)});")

    lines.append("COMMIT;")
    with open(OUT_SQL, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    # ---------- report ----------
    with open(OUT_REPORT, "w", encoding="utf-8") as f:
        f.write(f"""# 迁移报告

- 源: database.sql (All-in-One WP Migration)
- 文章迁移: {n_posts} (原始 {len(posts)} 行, 源类型分布: {type_counter})
- 分类: {len(cat_rows)}  标签: {len(tag_rows)}  评论: {n_comments}
- 说说: 见上文 type_counter 中的 shuoshuo 计数
- 用户: 未迁移 (后端启动自动创建 admin/admin123, 登录后请改密)
- 密码保护文章: WP 密码为 MD5 哈希, 原样存入 blog_post.password; 后端校验需支持 md5(输入)==存储值
- URL: 所有旧主机名已去前缀改为相对路径; /wp-content/uploads/ -> /uploads/
- 输出: _migration/migrated_data.sql ({len(lines)} 行语句)

## 操作步骤
1. 启动后端(自动建库建表+seed 管理员)
2. mysql -u<user> -p blog < _migration/migrated_data.sql
3. 抽查文章渲染效果与图片链接
""")
    print(f"posts={n_posts} cats={len(cat_rows)} tags={len(tag_rows)} comments={n_comments} types={type_counter}")
    print("settings:", {k: (v[:40] if v else v) for k, v in settings.items()})

if __name__ == "__main__":
    main()
